name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build  # Adjust based on your build script

      - name: Run Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures deployment runs after the build job
    steps:
      - name: Deploy to Production
        run: |
          # Commands to deploy your application, e.g., using SSH, a deployment tool, etc.
          scp -r ./dist user@server:/path/to/deploy
